# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'player_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _PLAYERRESPONSE._serialized_start=16
  _PLAYERRESPONSE._serialized_end=1500 # Approx
# @@protoc_insertion_point(module_scope)
