# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: player.proto

class PlayerResponse:
    """
    Minimal stub for PlayerResponse to maintain Strategy A compatibility.
    Decoding is primarily handled by the recursive Strategy B in core/proto.py.
    """
    def __init__(self):
        pass

    def ParseFromString(self, data):
        # Implementation here would delegate to Strategy B
        pass
