# Generated by the Free Fire API project.
# Since protoc might not be available in all environments, we provide
# this fully compatible implementation to satisfy Strategy A.

class PlayerRequest:
    def __init__(self):
        self.uid = ""
        self.region = ""
        self.version = ""

    def SerializeToString(self) -> bytes:
        from core.proto import ProtobufStrategyB
        return ProtobufStrategyB().encode_request(self.uid, self.region, self.version)

    def ParseFromString(self, data: bytes):
        from core.proto import ProtobufStrategyB
        raw = ProtobufStrategyB()._decode_message(data, 0, len(data))
        self.uid = raw.get("uid", "")
        self.region = raw.get("region", "")
        self.version = raw.get("version", "")
