# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

class PlayerRequest:
    def __init__(self):
        self.uid = ""
        self.region = ""
        self.version = ""

    def SerializeToString(self):
        # Minimal implementation of Protobuf encoding for PlayerRequest
        from core.proto import encode_request_raw
        return encode_request_raw(self.uid, self.region, self.version)
