# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: request.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
  name='request.proto',
  package='freefire',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rrequest.proto\x12\x08\x66reefire\",\n\rPlayerRequest\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0e\n\x06region\x18\x02 \x01(\tb\x06proto3'
)

_PLAYERREQUEST = _descriptor.Descriptor(
  name='PlayerRequest',
  full_name='freefire.PlayerRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='uid', full_name='freefire.PlayerRequest.uid', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='region', full_name='freefire.PlayerRequest.region', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=71,
)

DESCRIPTOR.message_types_by_name['PlayerRequest'] = _PLAYERREQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PlayerRequest = _reflection.GeneratedProtocolMessageType('PlayerRequest', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERREQUEST,
  '__module__' : 'request_pb2'
  # @@protoc_insertion_point(class_scope:freefire.PlayerRequest)
  })
_sym_db.RegisterMessage(PlayerRequest)
